# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Utility Library.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Debug'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: CmdLine@2
  inputs:
    script: 'mkdir $(System.DefaultWorkingDirectory)\lib'

- task: DownloadSecureFile@1
  name: 'secureFile'
  inputs:
    secureFile: '8d8fc771-9f32-49a5-a417-5c665d3fe605'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(secureFile.secureFilePath)'
    destinationFolder: '$(System.DefaultWorkingDirectory)/lib'
    cleanDestinationFolder: false

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/UtilityLibrary/bin/$(buildPlatform)/$(buildConfiguration)/'
    Contents: |
      UtilityLibrary.dll
      UtilityLibrary.pdb
    TargetFolder: '$(Build.ArtifactStagingDirectory)/UtilityLibrary'

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/UtilityLibrary'
    ArtifactName: 'UtilityLibrary'
    publishLocation: 'Container'